pcm.!default {
    type plug
    slave {
        pcm "hdmi_wrapper"
    }
}

pcm.hdmi_wrapper {
    type iec958
    slave {
        pcm "hw:2,0"
        format IEC958_SUBFRAME_LE
    }
}

ctl.!default {
    type hw
    card 2
}
