pcm.hdmi_out {
    type iec958
    slave {
        pcm "hw:0,0"
        format IEC958_SUBFRAME_LE
    }
}

pcm.analog {
    type plug
    slave {
        pcm "hw:1,0"
    }
}

#
# Active output selection
#
pcm.output {
    type plug
    slave {
        pcm "analog"
        # change to "hdmi_out" -or- "analog"
    }
}

pcm.!default {
    type plug
    slave {
        pcm "output"
    }
}

ctl.!default {
    type hw
    card 1
}
